local map = require('cosmic.utils').map
map("n", "L", ":BufferLineCycleNext <CR>")
map("n", "H", ":BufferLineCyclePrev <CR>")
map("n", "<A-1>", ":BufferLineGoToBuffer 1 <CR>")
map("n", "<A-2>", ":BufferLineGoToBuffer 2 <CR>")
map("n", "<A-3>", ":BufferLineGoToBuffer 3 <CR>")
map("n", "<A-4>", ":BufferLineGoToBuffer 4 <CR>")
map("n", "<A-5>", ":BufferLineGoToBuffer 5 <CR>")
map("n", "<A-6>", ":BufferLineGoToBuffer 6 <CR>")
map("n", "<A-7>", ":BufferLineGoToBuffer 7 <CR>")
map("n", "<A-8>", ":BufferLineGoToBuffer 8 <CR>")
map("n", "<A-9>", ":BufferLineGoToBuffer 9 <CR>")
